1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [79]:
import numpy as np
def vandy(l,n = None,inc=False):
    if n == None:
        #when n value is not specified it takes the length of the vector
        n = len(l)
    #when inc = True
    if inc == True:
        temp = np.array([y**i for y in l for i in range(n)]).reshape(len(l),n)
        print('vandermode matrix when inc = False:\n',temp)
    #when inc = False
    else:
        temp = np.array([y**i for y in l for i in range(n-1,-1,-1)]).reshape(len(l),n)
        print('vandermode matrix when inc = True:\n',temp)
    
#when Increasing is True
vandy([1,2,3,4],3,True)
#when Increasing is False
vandy([1,2,3,4],3,False) 

vandermode matrix when inc = False:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
vandermode matrix when inc = True:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br>
i 1 2 3 4 5 6 7 8 9 10<br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.<br>


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [102]:
def moving_averages(l,k):
    n = len(l)
    ma_list = [np.mean(l[i:i+k]) for i in range(n-k+1)]
    print('moving averages:\n',ma_list)
#caluclating moving averages for z with window size of w =3
z = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
w = 3
moving_averages(z,w)       

moving averages:
 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
